baseURL = "https://tchoupapps.fr"
languageCode = "fr-fr"
title = "Tchoupapps-fr"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 43

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 42

[markup.goldmark.renderer]
unsafe= true